name: build

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc11, clang14]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Building (release-x64)
        uses: docker://ghcr.io/nfrechette/toolchain-amd64-focal:v1
        with:
          args: 'python3 make.py -ci -compiler ${{ matrix.compiler }} -config Release -cpu x64 -build'

  osx-14:
    runs-on: macos-14
    strategy:
      matrix:
        compiler: [xcode16]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup ${{ matrix.compiler }} compiler
        run: ./tools/setup_osx_compiler.sh ${{ matrix.compiler }}
      - name: Building (release-arm64)
        run: python3 make.py -ci -compiler osx -config Release -cpu arm64 -build

  windows:
    runs-on: windows-2019
    strategy:
      matrix:
        compiler: [vs2019]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Building (release-x64)
        run: python3 make.py -ci -compiler ${{ matrix.compiler }} -config Release -cpu x64 -build
